### ISSUE TITLE
Add "Show selected apps" feature.

### ISSUE THREAD

**Issue by gaurav133** [gaurav133/PhoneUse#103]

**Comment by AnuragSingla911** [comment]
ui is completed

**Comment by gaurav133** [comment]
Feature complete. If there's a better way for doing same thing, would like to know to improve performance.

**Comment by gaurav133** [comment]
Need to try alternative way to verify the better out of the two.

**Comment by gaurav133** [comment]
Presently freeze current implementation.

**Comment by AnuragSingla911** [comment]
completed
