### ISSUE TITLE
Out of memory error in MusicListAdapter.

### ISSUE THREAD

**Issue by gaurav133** [gaurav133/PhoneUse#106]
![oomerror](https://cloud.githubusercontent.com/assets/1591207/8395081/bf9d6126-1d76-11e5-8749-79c60e70b84a.jpg)

**Comment by AnuragSingla911** [comment]
scenrio??

**Comment by AnuragSingla911** [comment]
is it repdroduce again??

**Comment by gaurav133** [comment]
No, once issue. Logs attached. No particular scenario.
