### ISSUE TITLE
Fab animation is not smooth in case of started service.

### ISSUE THREAD

**Issue by gaurav133** [gaurav133/PhoneUse#132]
This happens as data is fetched from DB on UI thread, maybe Async task can be used for this.

**Comment by AnuragSingla911** [comment]
will work on it tomorrow

**Comment by gaurav133** [comment]
After putting data loading in async task, this issue is fixed.

**Comment by AnuragSingla911** [comment]
need to check in slow L device

**Comment by gaurav133** [comment]
Fixed, closing.
