### ISSUE TITLE
Music data is incorrect on service stopped.

### ISSUE THREAD

**Issue by gaurav133** [gaurav133/PhoneUse#87]

**Comment by gaurav133** [comment]
The problem was in case of running service, instead of stopped service. Fix is ready for this. Testing.

**Comment by gaurav133** [comment]
Fixed. @AnuragSingla911 Please test this on your end and update.

**Comment by AnuragSingla911** [comment]
will wait and test it 1 or 2 days

**Comment by AnuragSingla911** [comment]
issue is fixed. hence closing
