### ISSUE TITLE
Add crash handler to application.

### ISSUE THREAD

**Issue by gaurav133** [gaurav133/PhoneUse#90]

**Comment by gaurav133** [comment]
ACRA library added.

**Comment by gaurav133** [comment]
Verifying if there's a global crash handler to prevent users from noticing FC.

**Comment by gaurav133** [comment]
@AnuragSingla911 Do we need to show (Unfortunately, phoneUse has stopped popup?), or skip it?. Other than that, I think this issue is resolved. Please verify from your end.

**Comment by AnuragSingla911** [comment]
if we can hide this that will be better

**Comment by gaurav133** [comment]
Fix sent for review to hide Android default FC dialog.

**Comment by gaurav133** [comment]
Fixed, need to verify on Samsung L devices.

**Comment by AnuragSingla911** [comment]
on L devices, popup still comming.. need to find alternate or let it MCS for now.

**Comment by gaurav133** [comment]
What to do regarding this issue?

**Comment by AnuragSingla911** [comment]
seems no solution for this issue. for the time, closing it
